// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// 02-lotriProp.h
double lotriMaxNu(SEXP lotri);
extern "C" SEXP _lotri_lotriMaxNu(SEXP lotri) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(lotriMaxNu(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(lotri)));
  END_CPP4R
}
// 03-lotriLstToMat.h
SEXP lotriLstToMat(SEXP lst_, SEXP format, SEXP startNum, SEXP matCls);
extern "C" SEXP _lotri_lotriLstToMat(SEXP lst_, SEXP format, SEXP startNum, SEXP matCls) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(lotriLstToMat(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(lst_), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(format), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(startNum), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(matCls)));
  END_CPP4R
}
// 05-asLotriMat.h
SEXP asLotriMat(SEXP x, cpp4r::list extra, cpp4r::strings def);
extern "C" SEXP _lotri_asLotriMat(SEXP x, SEXP extra, SEXP def) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(asLotriMat(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x), cpp4r::as_cpp<cpp4r::decay_t<cpp4r::list>>(extra), cpp4r::as_cpp<cpp4r::decay_t<cpp4r::strings>>(def)));
  END_CPP4R
}
// 06-lotriAllNames.h
cpp4r::writable::strings lotriAllNames(SEXP lotri);
extern "C" SEXP _lotri_lotriAllNames(SEXP lotri) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(lotriAllNames(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(lotri)));
  END_CPP4R
}
// 07-lotriBounds.h
SEXP lotriGetBounds(SEXP lst, SEXP format, SEXP startNum);
extern "C" SEXP _lotri_lotriGetBounds(SEXP lst, SEXP format, SEXP startNum) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(lotriGetBounds(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(lst), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(format), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(startNum)));
  END_CPP4R
}
// 08-nearPD.h
SEXP nearPD_(cpp4r::doubles_matrix<> x_r, bool keepDiag, bool do2eigen, bool doDykstra, bool only_values, double eig_tol, double conv_tol, double posd_tol, int maxit, bool trace);
extern "C" SEXP _lotri_nearPD_(SEXP x_r, SEXP keepDiag, SEXP do2eigen, SEXP doDykstra, SEXP only_values, SEXP eig_tol, SEXP conv_tol, SEXP posd_tol, SEXP maxit, SEXP trace) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(nearPD_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles_matrix<>>>(x_r), cpp4r::as_cpp<cpp4r::decay_t<bool>>(keepDiag), cpp4r::as_cpp<cpp4r::decay_t<bool>>(do2eigen), cpp4r::as_cpp<cpp4r::decay_t<bool>>(doDykstra), cpp4r::as_cpp<cpp4r::decay_t<bool>>(only_values), cpp4r::as_cpp<cpp4r::decay_t<double>>(eig_tol), cpp4r::as_cpp<cpp4r::decay_t<double>>(conv_tol), cpp4r::as_cpp<cpp4r::decay_t<double>>(posd_tol), cpp4r::as_cpp<cpp4r::decay_t<int>>(maxit), cpp4r::as_cpp<cpp4r::decay_t<bool>>(trace)));
  END_CPP4R
}
// 09-rcm.h
cpp4r::doubles_matrix<> rcm(cpp4r::doubles_matrix<> x);
extern "C" SEXP _lotri_rcm(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(rcm(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles_matrix<>>>(x)));
  END_CPP4R
}
// main.cpp
cpp4r::writable::list lotriSep(cpp4r::list lotri, SEXP above, cpp4r::integers below, SEXP aboveStart, SEXP belowStart);
extern "C" SEXP _lotri_lotriSep(SEXP lotri, SEXP above, SEXP below, SEXP aboveStart, SEXP belowStart) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(lotriSep(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::list>>(lotri), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(above), cpp4r::as_cpp<cpp4r::decay_t<cpp4r::integers>>(below), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(aboveStart), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(belowStart)));
  END_CPP4R
}
// main.cpp
bool isLotri(SEXP lotri);
extern "C" SEXP _lotri_isLotri(SEXP lotri) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(isLotri(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(lotri)));
  END_CPP4R
}
// main.cpp
cpp4r::writable::list getLotriPointers();
extern "C" SEXP _lotri_getLotriPointers() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(getLotriPointers());
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_lotri_asLotriMat",       (DL_FUNC) &_lotri_asLotriMat,        3},
    {"_lotri_getLotriPointers", (DL_FUNC) &_lotri_getLotriPointers,  0},
    {"_lotri_isLotri",          (DL_FUNC) &_lotri_isLotri,           1},
    {"_lotri_lotriAllNames",    (DL_FUNC) &_lotri_lotriAllNames,     1},
    {"_lotri_lotriGetBounds",   (DL_FUNC) &_lotri_lotriGetBounds,    3},
    {"_lotri_lotriLstToMat",    (DL_FUNC) &_lotri_lotriLstToMat,     4},
    {"_lotri_lotriMaxNu",       (DL_FUNC) &_lotri_lotriMaxNu,        1},
    {"_lotri_lotriSep",         (DL_FUNC) &_lotri_lotriSep,          5},
    {"_lotri_nearPD_",          (DL_FUNC) &_lotri_nearPD_,          10},
    {"_lotri_rcm",              (DL_FUNC) &_lotri_rcm,               1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_lotri(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
