# Generated by cpp4r: do not edit by hand

#' @title Maximum nu from lotri Object
#' @description Get the maximum nu value from a lotri matrix object.
#' @param lotri A lotri object
#' @return Maximum nu value as a double
#' @keywords internal
lotriMaxNu <- function(lotri) {
	.Call(`_lotri_lotriMaxNu`, lotri)
}

#' @title Convert List to Matrix
#' @description Convert a list of matrices to a single block-diagonal matrix.
#' @param lst_ A list of matrices
#' @param format Format string for naming
#' @param startNum Starting number for formatted names
#' @param matCls Matrix class
#' @return A block-diagonal matrix
#' @keywords internal
lotriLstToMat <- function(lst_, format, startNum, matCls) {
	.Call(`_lotri_lotriLstToMat`, lst_, format, startNum, matCls)
}

#' @title Convert Matrix to lotri Object
#' @description Convert a named symmetric matrix to a lotri object with optional
#'   bounds and other properties.
#' @param x A completely named symmetric matrix
#' @param extra A list of extra properties (lower, upper bounds, etc.)
#' @param def Default name for the matrix block (string of length 1)
#' @return A lotri object
#' @keywords internal
asLotriMat <- function(x, extra, def) {
	.Call(`_lotri_asLotriMat`, x, extra, def)
}

#' @title Get All Names from lotri Object
#' @description Extract all parameter names from a lotri matrix object.
#' @param lotri A lotri object (matrix or list of matrices)
#' @return Character vector of all parameter names
#' @keywords internal
lotriAllNames <- function(lotri) {
	.Call(`_lotri_lotriAllNames`, lotri)
}

#' @title Get Bounds from lotri Object
#' @description Extract lower and upper bounds from a lotri matrix object.
#' @param lst A lotri list object
#' @param format Optional format string for naming
#' @param startNum Starting number for formatted names
#' @return A list with 'lower' and 'upper' named numeric vectors
#' @keywords internal
lotriGetBounds <- function(lst, format, startNum) {
	.Call(`_lotri_lotriGetBounds`, lst, format, startNum)
}

#' @title Nearest Positive Definite Matrix
#' @description Compute the nearest positive definite matrix to an approximate one,
#'   typically a correlation or variance-covariance matrix.
#' @param x_r A symmetric matrix
#' @param keepDiag Logical indicating if the diagonal should be preserved
#' @param do2eigen Logical indicating if eigenvalue step should be performed
#' @param doDykstra Logical indicating if Dykstra's correction should be used
#' @param only_values Logical indicating if only eigenvalues should be returned
#' @param eig_tol Tolerance for eigenvalue positiveness
#' @param conv_tol Convergence tolerance for the algorithm
#' @param posd_tol Tolerance for enforcing positive definiteness
#' @param maxit Maximum number of iterations
#' @param trace Logical indicating if iterations should be traced
#' @return The nearest positive definite matrix, or eigenvalues if only_values is
#' TRUE
#' @keywords internal
nearPD_ <- function(x_r, keepDiag, do2eigen, doDykstra, only_values, eig_tol, conv_tol, posd_tol, maxit, trace) {
	.Call(`_lotri_nearPD_`, x_r, keepDiag, do2eigen, doDykstra, only_values, eig_tol, conv_tol, posd_tol, maxit, trace)
}

#' @title Use the RCM algorithm to permute to banded matrix
#' @description The RCM stands for the reverse Cuthill McKee (RCM) algorithm
#'   which is used to permute the matrix to a banded matrix.
#' @param x A symmetric matrix
#' @return A permuted matrix that should be banded
#' @export
#' @examples
#' m <- lotri({
#'  a + b + c + d + e + f + g + h + i + j + k + l + m + n + o +
#'  p ~ c(0.4, 0, 0.3, 0, 0, 0, -0.1, 0, 0, 0.2, 0, 0, 0,
#'        0, 0.5, 0, 0, 0, 0, 0, 1.3, 0, 0, 0, 0, 0, -0.6, 0.8,
#'        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2,
#'        0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0,
#'        0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.2, 0, 0.3,
#'        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2.1, 0.2, 0, 0, 0.2,
#'        0, 0, 0, 0, 0, 0, 0, 0, 0, 0.4, 0, 0, 0, 0, 0, -1.1,
#'        0.9, 0, 0, 0, 0, 0, 0, 0, 4.7, 0, 0, 0, 0, 0, 0, 0, 0,
#'        0, 0.5, 0, 0.2, 0, 0, 0, 1.9)
#' })
#' 
#' rcm(m)
rcm <- function(x) {
	.Call(`_lotri_rcm`, x)
}

#' @title Separate lotri Matrix into Above and Below
#' @description Separate a lotri matrix into components above and below certain
#' thresholds.
#' @param x A lotri matrix object
#' @param above Named integer vector for 'above' components
#' @param below Named integer vector for 'below' components
#' @param aboveStart Starting number for above formatting
#' @param belowStart Starting number for below formatting
#' @return A list with 'above' and 'below' components
#' @keywords internal
lotriSep <- function(lotri, above, below, aboveStart, belowStart) {
	.Call(`_lotri_lotriSep`, lotri, above, below, aboveStart, belowStart)
}

#' @title Check if Object is a lotri Object
#' @description Check if an R object is a valid lotri object.
#' @param lotri An R object to check
#' @return Logical indicating if the object is a lotri object
#' @keywords internal
isLotri <- function(lotri) {
	.Call(`_lotri_isLotri`, lotri)
}

#' @title Get lotri C Function Pointers
#' @description Get external pointers to lotri's C functions for use by other
#' packages.
#' @return A named list of external pointers to C functions
#' @keywords internal
getLotriPointers <- function() {
	.Call(`_lotri_getLotriPointers`)
}
